# Licensed under the Apache-2.0 license

[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "xtask"
publish.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
asn1 = { workspace = true, features = ["std"] }
caliptra-dpe-dice-asn1 = { path = "../dice-asn1" }
clap.workspace = true
hex = "0.4.3"
num_cpus = "1.17.0"
