# Licensed under the Apache-2.0 license

[package]
name = "platform"
version = "0.1.0"
edition = "2021"

[features]
default = ["dpe_profile_p256_sha256"]
openssl = ["dep:openssl"]
dpe_profile_p256_sha256 = []
dpe_profile_p384_sha384 = []

[dependencies]
openssl = {version = "0.10.57", optional = true}
ufmt = { git = "https://github.com/korran/ufmt.git", rev = "1d0743c1ffffc68bc05ca8eeb81c166192863f33", features = ["inline"] }
