# Licensed under the Apache-2.0 license

[package]
name = "platform"
version = "0.1.0"
edition = "2021"

[features]
openssl = ["dep:openssl"]
default = ["dpe_profile_p256_sha256"]
dpe_profile_p256_sha256 = []
dpe_profile_p384_sha384 = []

[dependencies]
openssl = {version = "0.10", optional = true}