name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # The runner image has rustup with stable (with clippy and rustfmt). So we
      # just need to update to use the most recent stable.
      - run: rustup update
      - run: ./ci.sh
