name: License checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_file_headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: check license header
        run: ci-tools/file-header-fix.sh --check
